### ISSUE TITLE
是否可以有个命令行接口

### ISSUE THREAD

**Issue by dourgulf** [YQqiang/EncryptDBUI#2]
这样更方便和其他工具集成使用

**Comment by YQqiang** [comment]
您好，您是需要在命令行中对数据库进行加密、解密操作吗？
这样的话，您可以参考下 SQLCipher 的文档：https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export
![image](https://user-images.githubusercontent.com/19221508/121450221-e2792180-c9cd-11eb-8739-7d2eb507f5a9.png)

**Comment by dourgulf** [comment]
噢，3Q
